name: fotoarkivet
favicon: null
layout_spectrum: 0.99232
typography_spectrum: 0.74689
title: Fotoarkivet Jon Fjeldstad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#354151'
    - '#c2d0ad'
    - '#8c86aa'
    - '#357b46'
  brandStrength: 0.5
  lightness: 0.6222282245289534
  saturation: 0.75
  rhythmicContrast: 0.9838381786830723
purpose: []
