name: fotoarkivet
favicon: null
layout_spectrum: 0.3623755674343556
typography_spectrum: 0.6518473848700523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7786825029179454
  lightness: 0.6222282245289534
  saturation: 0.8931234718766063
  rhythmicContrast: 0.9838381786830723
purpose: []
